Buildalyzer/Buildalyzer

.gitignore, NetCoreTests/NetCoreTestFixture.cs, NetCoreTests/NetCoreTests.csproj
Also added Rider and VsCode to .gitignore.
=> Fix tests when not running under Windows

Buildalyzer.Workspaces.Tests/ProjectAnalyzerExtensionsFixture.cs, Buildalyzer.Workspaces/ProjectAnalyzerExtensions.cs
Could probably add more of the parameters to CompilationOptions given the metadata we have, but this is a good starting point.
=> Add CompilationOptions to Project

src/Buildalyzer/AnalyzerManager.cs, src/Buildalyzer/ProjectAnalyzer.cs
=> Allow the Clean before Compile to be turned off

src/Buildalyzer/AssemblyResolver.cs, src/Buildalyzer/Environment/EnvironmentFactory.cs
See discussion here: https://github.com/daveaglick/Buildalyzer/issues/65
=> Cross system portable paths

src/Buildalyzer.Workspaces/AnalyzerResultExtensions.cs
=> Add the ability to clear the project references from the cache

src/Buildalyzer/AnalyzerResult.cs
- Add property for quickly accessing package references.
=> Add PackageReferences

.gitignore, src/Buildalyzer/Environment/EnvironmentFactory.cs, tests/Buildalyzer.Tests/Integration/OpenSourceProjectsFixture.cs
Change to logic for msbuild.exe  discovery
=> change msbuild discovery path logic

src/Buildalyzer.Workspaces/Buildalyzer.Workspaces.csproj
Needed to support c#8 features
=> Update dependencies in Buildalyzer.Workspaces.csproj

src/Buildalyzer.Workspaces/AnalyzerManagerExtensions.cs, src/Buildalyzer.Workspaces/AnalyzerResultExtensions.cs, src/Buildalyzer.Workspaces/ProjectAnalyzerExtensions.cs, src/Buildalyzer/AnalyzerManager.cs, src/Buildalyzer/AnalyzerResult.cs, src/Buildalyzer/AnalyzerResults.cs, src/Buildalyzer/Construction/IPackageReference.cs, src/Buildalyzer/Construction/IProjectFile.cs, src/Buildalyzer/Construction/PackageReference.cs, src/Buildalyzer/Construction/ProjectFile.cs, src/Buildalyzer/Environment/EnvironmentFactory.cs, src/Buildalyzer/IAnalyzerManager.cs, src/Buildalyzer/IAnalyzerResult.cs, src/Buildalyzer/IAnalyzerResults.cs, src/Buildalyzer/IProjectAnalyzer.cs, src/Buildalyzer/ProjectAnalyzer.cs, tests/Buildalyzer.Tests/Integration/OpenSourceProjectsFixture.cs, tests/Buildalyzer.Tests/Integration/SimpleProjectsFixture.cs, tests/Buildalyzer.Workspaces.Tests/ProjectAnalyzerExtensionsFixture.cs
This PR adds interfaces to the classes I would like to be able to mock for unit testing perposes.
closes #102
=> Add interfaces

src/Buildalyzer/AnalyzerResults.cs, src/Buildalyzer/ProjectAnalyzer.cs
Implemented fixes suggested for #134 and #138, could not do any further testing.
=> Implemented two suggested fixes for concurrency issues

src/Buildalyzer.Logger/BuildalyzerLogger.cs, src/Buildalyzer/AnalyzerResult.cs, src/Buildalyzer/Environment/ProcessRunner.cs, src/Buildalyzer/Logging/EventProcessor.cs, src/Buildalyzer/ProjectAnalyzer.cs
now stores the output of corecompile and thus gives the sourcefiles and references of an F# project
=> extra-fsharp-features

src/Buildalyzer/Environment/EnvironmentFactory.cs
=> Make sure IsFrameworkTargetFramework doesn't detect net5.0

src/Buildalyzer.Workspaces/AnalyzerResultExtensions.cs
Fixes https://github.com/daveaglick/Buildalyzer/issues/168.
I didn't add a test, because I think doing that would require creating a separate test project just for this case, and I don't think that would be worth it.
=> Extract language-specific code into local functions

src/Buildalyzer/Construction/PackageReference.cs, tests/Buildalyzer.Tests/Construction/PackageReferenceFixture.cs
If `Include` is not set, try `Update`
Fixes #170
=> Add support for update property

src/Buildalyzer/AnalyzerResult.cs
forgot to remove this in the previous PR's
=> Small QOL change needed when using Buildalyzer F#

src/Buildalyzer/Construction/IProjectFile.cs, src/Buildalyzer/Construction/ProjectFile.cs, src/Buildalyzer/ProjectAnalyzer.cs
=> Fixing ProjectAnalyzer exceptions when solution file is not in the source root

tests/Buildalyzer.Tests/Integration/OpenSourceProjectsFixture.cs
See https://github.com/daveaglick/Buildalyzer/issues/185
=> Added hello-world test case for net 6.0 projects

src/Buildalyzer.Workspaces/AnalyzerResultExtensions.cs, src/Buildalyzer/AnalyzerResult.cs, tests/Buildalyzer.Tests/Integration/SimpleProjectsFixture.cs, tests/projects/DuplicateProjectReferences/DependentProject/DependentProject.csproj, tests/projects/DuplicateProjectReferences/DependentProject/LibInterface.cs, tests/projects/DuplicateProjectReferences/DependentProject/Properties/AssemblyInfo.cs, tests/projects/DuplicateProjectReferences/MainProject/App.config, tests/projects/DuplicateProjectReferences/MainProject/MainProject.csproj, tests/projects/DuplicateProjectReferences/MainProject/MainProject.sln, tests/projects/DuplicateProjectReferences/MainProject/Program.cs, tests/projects/DuplicateProjectReferences/MainProject/Properties/AssemblyInfo.cs
This is to resolve issue #203.
=> Make sure all project references are distinct

azure-pipelines.yml
Adding azure pipeline for publish.
=> chore: add pipeline for publish

src/Buildalyzer/AnalyzerManagerOptions.cs, src/Buildalyzer/AnalyzerResult.cs, src/Buildalyzer/AnalyzerResults.cs, src/Buildalyzer/Compiler/FSharpCompilerCommand.cs, src/Buildalyzer/Construction/IProjectFile.cs, src/Buildalyzer/Construction/ProjectFile.cs, src/Buildalyzer/EmptyDisposable.cs, src/Buildalyzer/Environment/EnvironmentOptions.cs, src/Buildalyzer/Environment/MsBuildProperties.cs, src/Buildalyzer/Guard.cs, src/Buildalyzer/IAnalyzerManager.cs, src/Buildalyzer/IAnalyzerResult.cs, src/Buildalyzer/IAnalyzerResults.cs, src/Buildalyzer/IProjectAnalyzer.cs, src/Buildalyzer/IProjectItem.cs, src/Buildalyzer/Logging/TextWriterLogger.cs, src/Buildalyzer/ProjectAnalyzer.cs, src/Buildalyzer/ProjectItem.cs, src/Buildalyzer/XDocumentExtensions.cs, tests/Buildalyzer.Tests/Construction/PackageReferenceFixture.cs, tests/Buildalyzer.Tests/Environment/EnvironmentFactoryFixture.cs, tests/Buildalyzer.Tests/Properties/GlobalUsings.cs
=> Remove unused namespaces

Buildalyzer.sln, Directory.Build.props, package.props, src/Buildalyzer.Logger/Buildalyzer.Logger.csproj, src/Buildalyzer.Workspaces/Buildalyzer.Workspaces.csproj, src/Buildalyzer/Buildalyzer.csproj, tests/Buildalyzer.Tests/Buildalyzer.Tests.csproj, tests/Buildalyzer.Workspaces.Tests/Buildalyzer.Workspaces.Tests.csproj
For details, read [Proj0243](https://dotnet-project-file-analyzers.github.io/rules/Proj0243.html).
=> Generate software bill of materials
