FrameworkTests/FrameworkTestFixture.cs, FrameworkTests/FrameworkTests.csproj
These tests currently fail against .NET Core, as they're full framework tests this will only discover them when compiling against the full framework.
=> Hide full framework tests when on .NET Core

src/Buildalyzer.Workspaces/ProjectAnalyzerExtensions.cs
Hey guys! Thanks for the cool project :) It lets me easily upgrade a .NET Framework project that depends on the `Microsoft.CodeAnalysis.Workspace` stuff.
I used `Workspace` throughout my project and noticed the extensions methods expect an `AdhocWorkspace` even thought they don't have to.
=> Let Extensions take Workspace param instead of AdhocWorkspace

src/Buildalyzer/Environment/DotnetPathResolver.cs
Completely anecdotal but this fixed our `TeamCity` builds that were failing on this.
=> increase timeout to get the dotnet --info output from 1 to 4 seconds

Buildalyzer.sln, tests/FrameworkTests/FrameworkTestFixture.cs, tests/FrameworkTests/FrameworkTests.csproj, tests/FrameworkTests/app.config, tests/NetCoreTests/NetCoreTestFixture.cs, tests/projects/LegacyFrameworkProjectWithPackageReference/Class1.cs, tests/projects/LegacyFrameworkProjectWithPackageReference/LegacyFrameworkProjectWithPackageReference.csproj, tests/projects/LegacyFrameworkProjectWithPackageReference/Properties/AssemblyInfo.cs, tests/projects/TestProjects.sln
This PR adds tests for projects that use PackageReference instead of packages.config. Some of them are failing as noted in daveaglick/Buildalyzer#33.
=> Add tests for PackageReference projects

Buildalyzer.sln, src/Buildalyzer/ProjectAnalyzer.cs, tests/FrameworkTests/FrameworkTestFixture.cs, tests/NetCoreTests/NetCoreTestFixture.cs, tests/projects/SdkProjectWithImportedProps/Class1.cs, tests/projects/SdkProjectWithImportedProps/SdkProjectWithImportedProps.csproj, tests/projects/SdkProjectWithImportedProps/Test.props, tests/projects/TestProjects.sln
This resolves usage of properties like MSBuildThisFileDirectory in project files.
I had actually taken the code from Roslyn MSBuild Workspaces project:
https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Desktop/Workspace/MSBuild/ProjectFile/ProjectFileLoader.cs#L54
=> Changed MSBuild Project construction to set project file path

.gitignore, Buildalyzer.sln, README.md, ReleaseNotes.md, src/Buildalyzer/AnalyzerManager.cs, src/Buildalyzer/AnalyzerManagerOptions.cs, src/Buildalyzer/Environment/BuildEnvironment.cs, src/Buildalyzer/Environment/DotnetPathResolver.cs, src/Buildalyzer/ProjectAnalyzer.cs, src/Buildalyzer/ReleaseNotes.md
Adds ability to set Global Properties at the `AnalyzerManager` level. Also allows setting environment variables and fixes global property leak when sharing a `BuildEnvironment`.
Closes #52
=> Adds ability to set Global Properties at the AnalyzerManager level

src/Buildalyzer/AssemblyResolver.cs, src/Buildalyzer/Buildalyzer.csproj, src/Buildalyzer/Environment/EnvironmentFactory.cs
There's a dependency transitivity issue (e.g., Roslyn and logging) that "forces" me to upgrade these packages. Note that my commits from the other cross-platform PR are also here (feel free to cherry-pick).
=> Upgrade depending packages [account for transitivities]

src/Buildalyzer/Environment/EnvironmentFactory.cs
This PR fixes ArgumentException when following key exists in EnvironmentOption.EnvironmentVariables.
* MSBuildSDKsPath
* MSBuildExtensionsPath
=> avoid exception when adding specific property in EnvironmentOption

src/Buildalyzer/Environment/BuildEnvironment.cs, src/Buildalyzer/Environment/DotnetPathResolver.cs, src/Buildalyzer/Environment/EnvironmentFactory.cs, src/Buildalyzer/Environment/EnvironmentOptions.cs, src/Buildalyzer/ProjectAnalyzer.cs
when I want to use daily SDK build, I use zip-deployed SDK(currently, dotnet-sdk-3.0.100-*).
Currently, I must prepend custom sdk's dotnet.exe directory path to  "PATH" env.
Because environment variable may have session-global effect, I want to avoid setting PATH env.
adding "DotNetExePath" to EnvironmentOptions, and then use it in build.
=> add dotnet.exe setting variable for zip deployed SDK

src/Buildalyzer.Workspaces/AnalyzerManagerExtensions.cs
Parallelize the project builds when creating a workspace.  This massively reduces the time to generate the workspace for medium to large solutions.
I'm unsure about thread safety issues here and would welcome feedback but I did test this pretty extensively by loading a medium sized solution and generating a workspace 100 times in a loop.  I didn't see any errors and saw consistent structure in the generated workspace.
NOTE: I tested this on a branch that also had https://github.com/daveaglick/Buildalyzer/pull/90, otherwise I ran into warnings because the dotnet --info output wasn't being fully parsed.
=> Parallelize project builds during workspace creation

src/Buildalyzer/AnalyzerResult.cs, tests/Buildalyzer.Tests/AnalyzerResultFixture.cs
I found that `ProcessCscCommandLine` won't parse `/reference:Alias="path"` format arguments as expected.
**Input**
```
csc.exe /reference:Data1="C:\Program Files(x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Data.dll"
```
**Actual**
```
(null, "csc.exe")
("reference", "Data1=\"C:\\Program")
(null, "Files(x86)\\Reference")
(null, "Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\System.Data.dll\"")
```
**Expected**
```
(null, "csc.exe")
("reference", "Data1=C:\\Program Files(x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6.2\\System.Data.dll")
```
To fix this problem, I rewrote `ProcessCscCommandLine`.
And I think the test cases of `ParsesCscCommandLineSourceFiles` are incorrect as to escaping `"`. This screenshot shows how `cmd` …
=> Cannot parse `/reference:Alias="path"` format arguments

src/Buildalyzer/Construction/PackageReference.cs, src/Buildalyzer/Construction/ProjectFile.cs
Add the ability to get package references with name and (optional) version.
Helps with #110
=> Add package references to project file

src/Buildalyzer/Environment/DotnetPathResolver.cs, src/Buildalyzer/Environment/EnvironmentFactory.cs, src/Buildalyzer/Environment/EnvironmentVariables.cs
When working on .NET Core, if environment variable "COREHOST_TRACE" is set to 1, huge amounts of debug text is printed within dotnet commands.
This debug text makes Buildalyzer freeze (wait longer than a minute to fetch .NET SDK path, in method DotnetPathResolver.GetInfo)
Disabling this environment variable on dotnet command processes makes Buildalyzer run on expected speeds again.
=> disable env var "COREHOST_TRACE" for .NET Core

src/Buildalyzer/Environment/DotnetPathResolver.cs
When trying to find the default SDK and there isn't a global.json the default SDK finder sometimes throw a ArgumentOutOfRange exception because the line breaks between sections in the output from `dotnet --info` is missing for some reason.
This commit fixes one of those scenarios while keeping the original way of finding the SDK intact.
=> Fix for finding the default SDK in some scenarios

src/Buildalyzer.Logger/Buildalyzer.Logger.csproj, src/Buildalyzer.Workspaces/Buildalyzer.Workspaces.csproj, src/Buildalyzer/Buildalyzer.csproj, tests/Buildalyzer.Tests/Buildalyzer.Tests.csproj, tests/Buildalyzer.Workspaces.Tests/Buildalyzer.Workspaces.Tests.csproj
=> upgrading project and msbuild deps

src/Buildalyzer/ProjectAnalyzer.cs, tests/Buildalyzer.Tests/Integration/SimpleProjectsFixture.cs
The SolutionDir property does not end with a directory separator. This is different than how MSBuild sets this property:
=> The SolutionDir property is different from the MSBuild output 

src/Buildalyzer.Workspaces/AnalyzerResultExtensions.cs, src/Buildalyzer/AnalyzerResult.cs, src/Buildalyzer/IAnalyzerResult.cs, tests/Buildalyzer.Workspaces.Tests/ProjectAnalyzerExtensionsFixture.cs, tests/projects/SdkNetCoreProjectWithAnalyzer/Class1.cs, tests/projects/SdkNetCoreProjectWithAnalyzer/SdkNetCoreProjectWithAnalyzer.csproj
Fixes https://github.com/daveaglick/Buildalyzer/issues/157.
Note that source generators use the same mechanism of "analyzer" references, so this single change fixes both.
=> Added support for analyzers and source generators

src/Buildalyzer.Workspaces/Buildalyzer.Workspaces.csproj
In my project, I want to have:
```csproj
<PackageReference Include="Buildalyzer.Workspaces" Version="3.1.0" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.0" />
```
which gives me following version conflict error:
```txt
myproject.csproj : error NU1107: Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.7.0 directly to project myproject to resolve this issue. 
myproject.csproj : error NU1107:  myproject -> Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 5.0.0 -> Microsoft.CodeAnalysis.Razor 5.0.0 -> Microsoft.CodeAnalysis.Common (>= 3.7.0)
myproject.csproj : error NU1107:  myproject -> Buildalyzer.Workspaces 3.1.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 3.6.0 -> …
```
=> Bump `Microsoft.CodeAnalysis` packages to 3.7.0

src/Buildalyzer/AnalyzerResult.cs, src/Buildalyzer/IAnalyzerResult.cs, src/Buildalyzer/IProjectItem.cs, src/Buildalyzer/ProjectItem.cs
Since the constructor of ProjectItem is internal it is very hard to mock the IAnalyzerResult properly.
Suggested improvement for: #161
=> Add an interface for ProjectItem

src/Buildalyzer.Workspaces/AnalyzerResultExtensions.cs, tests/Buildalyzer.Workspaces.Tests/ProjectAnalyzerExtensionsFixture.cs
Fixes #159 
This change adds to the functionality when you set `addProjectReferences` to `true`. At the moment it will follow all references where you have already added the project to the solution, but if you want to create an ad-hoc solution with a csproj as the entry point, I think you'll want this behaviour to automatically add references projects to the solution.
Just to be clear, the code change code (in `GetReferencedAnalyzerProjects`) is only called when `addProjectReferences` is `true`.
=> Add Referenced Projects

src/Buildalyzer.Workspaces/AnalyzerManagerExtensions.cs, tests/Buildalyzer.Workspaces.Tests/ProjectAnalyzerExtensionsFixture.cs
When creating a Workspace from an AnalyzerManager created from a solution file, this change ensures that `CurrentSolution.FilePath` is set correctly.
There were some failing integration tests but I think they're due to my environment being different.
=> When SolutionFilePath is available set in Workspace Solution

src/Buildalyzer/Environment/BuildEnvironment.cs, src/Buildalyzer/Environment/MsBuildProperties.cs
In general this can be considered an optimization, but it also fixes an error that I'm running into where msbuild tries to copy the `apphost.exe`, but it doesn't exist.
I'd like to understand why it fails, but at the same time, a design-time build probably should be switching this off.
=> Disable AppHost Creation

src/Buildalyzer/Environment/BuildEnvironment.cs, src/Buildalyzer/ProjectAnalyzer.cs
If null or an empty string is provided for msBuildExePath parameter of BuildEnvironment constructor, but a path to dotnet.exe is provided in the dotnetExePath parameter, then this will now work by only calling dotnet.exe without any MSBuild involvement, so this library can then be used with dotnet.exe alone too. We need this functionality now that some of our solutions have been ported to net5/net6 and are built with dotnet.exe and functionalities which are only provided via dotnet.exe.
=> Added capability to use dotnet.exe only without MSBuild.dll

src/Buildalyzer/Logging/EventProcessor.cs
I have yet another Pull Request :D But I don't know if or how you want to implement this, or if you can think of a better solution.
The thing is, with Visual Studio 2022 the TargetFrameworkMoniker is no longer generated for C++ projects even though it is told so (which kinda makes sense since there's no TargetFramework for C++ projects).
This change would use an empty string as the key for project properties if the TargetFrameworkMoniker property wasn't found so the analysis can be run for non C#/Framework projects too, especially C++ projects with Visual Studio 2022.
This would mean a change of behaviour since it will now work with projects it hasn't worked with on previous Visual Studio installations too, like installer projects. We could simply accept that or we could introduce an …
=> Use empty string as key for project properties if TargetFrameworkMonitor is not found

.gitignore, build/Buildalyzer.Build/Buildalyzer.Build.csproj, src/Buildalyzer.Logger/BuildalyzerLogger.cs, src/Buildalyzer.Workspaces/Buildalyzer.Workspaces.csproj, src/Buildalyzer/AnalyzerManager.cs, src/Buildalyzer/Buildalyzer.csproj, src/Buildalyzer/Logging/EventProcessor.cs, tests/Buildalyzer.Tests/Buildalyzer.Tests.csproj, tests/Buildalyzer.Tests/Integration/OpenSourceProjectsFixture.cs, tests/Buildalyzer.Workspaces.Tests/Buildalyzer.Workspaces.Tests.csproj, tests/Buildalyzer.Workspaces.Tests/ProjectAnalyzerExtensionsFixture.cs, tests/Buildalyzer.Workspaces.Tests/SafeStringWriter.cs
Another way of doing upgrade in comparison to
https://github.com/daveaglick/Buildalyzer/pull/189
=> Update Roslyn based libraries to 4.0.1 and use .NET 6 SDK with multitarget

src/Buildalyzer/AnalyzerResults.cs, src/Buildalyzer/Buildalyzer.csproj, src/Buildalyzer/TargetFrameworkComparer.cs, tests/Buildalyzer.Tests/Integration/SimpleProjectsFixture.cs
The order itself is not relevant (the `NuGetFrameworkSorter` used to sort target frameworks doesn't guarantee any specific order anyway) but the order is deterministic, meaning that several builds of the same project will always yield the same order of the target frameworks and results.
The nondeterministic nature of the current implementation made it hard to diagnose an implementation issue in Stryker.NET: https://github.com/stryker-mutator/stryker-net/issues/1899#issuecomment-1035432919
=> Make AnalyzerResults deterministically ordered

src/Buildalyzer/AnalyzerResult.cs, src/Buildalyzer/IAnalyzerResult.cs, tests/Buildalyzer.Tests/AnalyzerResultFixture.cs
=> Implement API to retrieve compiler command-line

src/Buildalyzer/AnalyzerResult.cs, tests/Buildalyzer.Tests/Integration/SimpleProjectsFixture.cs
That big LINQ query started to throw for F# since the first cmd-line argument is a tuple `(null, null)`.
In tests, it's enough to just call `SourceFiles`.
=> Fixed a NullReferenceException for F# projects

src/Buildalyzer.Workspaces/AnalyzerResultExtensions.cs
This PR fixes an issue where the `AnalyzerResultExtensions.GetAnalyzerReferences` method allows the return of relative paths instead of absolute paths as expected by Roslyn and causing an exception to be thrown.
Depending on the execution environment: from within Visual Studio, from the command line by running the executable, or via `dotnet run` some references may be passed in as relative paths. If these references are then passed to the Roslyn subsystem then you will see an exception similar to below (call stack has been abbreviated and code related to PR is highlighted):
```
Unhandled exception. System.ArgumentException: Absolute path expected. (Parameter 'fullPath')
***
at Roslyn.Utilities.CompilerPathUtilities.RequireAbsolutePath(String path, String argumentName)
at …
```
=> Convert relative paths to absolute paths for analyzer references

src/Buildalyzer.Workspaces/AnalyzerResultExtensions.cs, tests/Buildalyzer.Workspaces.Tests/ProjectAnalyzerExtensionsFixture.cs, tests/projects/NullabilityEnabled/NullabilityEnabled.csproj, tests/projects/NullabilityEnabled/SimpleModel.cs
I noticed that the [`NullableContextOptions`](https://sourceroslyn.io/#Microsoft.CodeAnalysis/Compilation/NullableContextOptions.cs) where not set while creating the `CSharpCompilationOptions`. With this PR, that should be fixed.
=> Support nullable context options

src/Buildalyzer/Environment/DotnetPathResolver.cs, src/Buildalyzer/Environment/EnvironmentVariables.cs
**Description**
In some scenarios 4000ms to execute the dotnet --info command is not enough.
**Objective** 
The objective is to add the possibility of passing the desired timeout via environment variable.
**Scenario**
I identified this scenario when running the solution within k8s clusters with low memory and CPU.
[Related Issue](https://github.com/daveaglick/Buildalyzer/issues/228)
=> Adding timeout to the dotnet info command, using environment variables.

src/Buildalyzer/AnalyzerResults.cs, tests/Buildalyzer.Tests/Integration/SimpleProjectsFixture.cs
Commit 8e85a15e324a65f9da5033f3d8a2320c76dda378 dropped the NuGet.Frameworks dependency and as a result sorting of the target frameworks behaviour changed.
Previously, the `NuGetFrameworkSorter` would sort the empty target framework last. Since 8e85a15e324a65f9da5033f3d8a2320c76dda378 the empty target framework is sorted first.
This commit restores the old behaviour of sorting the empty target framework last.
Note: Stryker.NET was inadvertently depending on this behaviour, so v6.0.1 broke Stryker.NET. I have [fixed the issue in Styker.NET](https://github.com/stryker-mutator/stryker-net/pull/2811) but I think restoring the previous sorting behaviour is a good idea anyway.
=> Restore sorting empty target framework last

src/Buildalyzer/Environment/BuildEnvironment.cs, src/Buildalyzer/Environment/MsBuildProperties.cs, tests/Buildalyzer.Tests/Buildalyzer.Tests.csproj, tests/Buildalyzer.Tests/Environment/MsBuildPropertiesFixture.cs, tests/Buildalyzer.Tests/Properties/GlobalUsings.cs
The **DesignTime** flag for creating a `BuildEnvironment` contains a set of properties that is set. By this change, those properties are easier to access.
=> Define the MS Build design time as read-only data structure

src/Buildalyzer/Buildalyzer.csproj, src/Buildalyzer/Environment/EnvironmentFactory.cs
`NuGetFramework` represents the target framework and its domain concerns. Thanks for the suggestion @rouke-broersma !
=> Use NuGetFramework to deal with TargetFramework logic

src/Buildalyzer/EmptyDisposable.cs, src/Buildalyzer/Logging/TextWriterLogger.cs
Providing `EmptyDisposable` as part of the public API should not be part of Buildalyzer. I've decorated it as `[Obsolete]` and created a private alternative for the place where it was actually used.
=> Drop `EmptyDisposable`

src/Buildalyzer/AnalyzerResult.cs, src/Buildalyzer/Compiler/CompilerItems.cs, src/Buildalyzer/Compiler/CompilerItemsCollection.cs, src/Buildalyzer/Compiler/CompilerProperties.cs, src/Buildalyzer/Compiler/CompilerProperty.cs, src/Buildalyzer/Diagnostics/CollectionDebugView.cs, src/Buildalyzer/IEnumerableExtensions.cs, src/Buildalyzer/Logging/EventProcessor.cs, src/Buildalyzer/Logging/PropertiesAndItems.cs, src/Buildalyzer/Properties/GlobalUsings.cs
While debugging #244, I noticed that debugging which compiler properties where active was not really clear. So similar to #243, I introduced two dedicated (read-only) types that contain the properties and the items. Potentiality, it can replace the dictionaries in the `AnalyzerResult`. That is, obviously a breaking change.
Under the hood, `CompilerProperties` and `CompilerItemsCollection` are dictionaries (with case-insensitive keys), but as I think (that can be challenged) having the values without the related key have less value in this case, the `TryGet()` method returns a `KeyValuePair` like struct that combines the two.
Let me know what you think.
=> Proposal: represent  of CompilerItems and CompilerProperties as dedicated types

src/Buildalyzer.Workspaces/AnalyzerManagerExtensions.cs, src/Buildalyzer.Workspaces/AnalyzerResultExtensions.cs, src/Buildalyzer/AnalyzerManager.cs, src/Buildalyzer/AnalyzerManagerOptions.cs, src/Buildalyzer/AnalyzerResult.cs, src/Buildalyzer/Compiler/Compiler.cs, src/Buildalyzer/Construction/ProjectFile.cs, src/Buildalyzer/Environment/BuildEnvironment.cs, src/Buildalyzer/Environment/EnvironmentFactory.cs, src/Buildalyzer/Guard.cs, src/Buildalyzer/ProjectAnalyzer.cs, tests/Buildalyzer.Tests/Compiler/CompilerCommandFixture.cs, tests/Buildalyzer.Tests/Integration/SimpleProjectsFixture.cs, tests/Buildalyzer.Workspaces.Tests/ProjectAnalyzerExtensionsFixture.cs
Applied some suggestions by static code analyzers.
=> Reduce issues

src/Buildalyzer/ProjectAnalyzer.cs
=> Escape semicolon in property values

src/Buildalyzer/ProjectAnalyzer.cs, tests/Buildalyzer.Tests/Integration/SimpleProjectsFixture.cs
Fixes #271
There are other solutions to this, like running `ReadAll` in a `Thread` or `Task` and aborting that. I've also looked at the cancellation token and using that, however it's not being used effectively in `ReadAll` and I don't think there is simple solution as `AnonymousPipeLoggerServer` doesn't support cooperative cancellation as far as I can see.
There may be a memory leak here with the the two events being subscribed to, not sure if we want to try and engineer a better solution.
=> Fix hang if build does not start

README.md, src/Buildalyzer/Environment/EnvironmentVariables.cs, src/Buildalyzer/ProjectAnalyzer.cs
If your application's output is a single file, you will need to provide the path to the following DLLs:
`-MsBuildPipeLogger.Logger.dll`
`-Buildalyzer.logger.dll`
Variable name: `LoggerPathDll`
See related issue [224](https://github.com/phmonte/Buildalyzer/issues/224)
msbuild needs the physical address of the logger, for this reason it is not possible to use single file publish without informing this route.
Remembering that if the files are in the root where the project is running, it is not necessary to inform the path.
[x] Readme updated
=> feat: adding alternative for single file publish

.editorconfig, src/Buildalyzer/Buildalyzer.csproj, src/Buildalyzer/Environment/BuildEnvironment.cs, src/Buildalyzer/Logging/EventProcessor.cs
The objective is to clean up the project by resolving most of the warnings, it's a long job, I'm trying to solve it in parts, I've been trying to do it in a single PR for a few days, but apparently it won't be possible, we have too many.
Next steps:
Evaluate other warnings.
=> chore: removing some warnings

src/Buildalyzer/AnalyzerResult.cs
To improve the debugger experience a `[DebuggerDisplay]` has been added to `AnalyzerResult`.
=> Add [DebuggerDisplay] to AnalyzerResult

src/Buildalyzer.Workspaces/Buildalyzer.Workspaces.csproj, src/Buildalyzer/Buildalyzer.csproj, tests/Buildalyzer.Tests/Integration/SimpleProjectsFixture.cs, tests/Buildalyzer.Workspaces.Tests/ProjectAnalyzerExtensionsFixture.cs, tests/projects/SdkNet8CS12FeaturesProject/Class1.cs, tests/projects/SdkNet8CS12FeaturesProject/SdkNet8CS12FeaturesProject.csproj, tests/projects/TestProjects.sln
Fixes #281
This PR updates MSbuild references to support C# 12 features which are not buildable using latest public version of Buildalyzer
A test case was added which would fail withouth this commit
=> Updates MSBuild references

src/Buildalyzer/Environment/DotNetInfoResolver.cs, src/Buildalyzer/Environment/ProcessRunner.cs, src/Buildalyzer/ProcessData.cs, src/Buildalyzer/ProcessDataCollector.cs
To reduce the responsibilities of different pieces of code, I think it is a good idea to let a dedicated collector take care of the collection of the  `DataReceivedEventArgs` events fired while running a `Process` in Buildalyzer.
=> Isolate the collection of the ProcessData

src/Buildalyzer/Buildalyzer.csproj, src/Buildalyzer/Compiler/FSharpCommandLineParser.cs, src/Buildalyzer/Compiler/RoslynCommandLineParser.cs, src/Buildalyzer/Construction/ProjectFile.cs, src/Buildalyzer/Environment/BuildEnvironment.cs, src/Buildalyzer/Environment/DotNetInfoParser.cs, src/Buildalyzer/Extensions/System.String.cs, src/Buildalyzer/IO/IOPath.cs, src/Buildalyzer/Logging/EventProcessor.cs, src/Buildalyzer/ProjectAnalyzer.cs, src/Buildalyzer/XDocumentExtensions.cs
To improve on the readability when comparing strings case insensitive, I've created 3 extension methods:
``` C#
namespace System;
internal static class BuildalyzerStringExtensions
{
public static bool IsMatch(this string? self, string? value);
public static bool IsMatchStart(this string self, string value);
public static bool IsMatchEnd(this string self, string value);
}
```
For obvious reasons this helpers are kept internal, as this should not be a deliverable of Buildalyzer.
=> Clean-up code by introducing String compare helpers

.github/workflows/build.yml, src/Buildalyzer.Workspaces/AnalyzerResultExtensions.cs, src/Buildalyzer/AnalyzerResult.cs, src/Buildalyzer/Compiler/Compiler.cs, src/Buildalyzer/Compiler/CompilerCommand.cs, src/Buildalyzer/IAnalyzerResult.cs, src/Buildalyzer/Logging/EventProcessor.cs, tests/Buildalyzer.Tests/Integration/SimpleProjectsFixture.cs, tests/Buildalyzer.Workspaces.Tests/ProjectAnalyzerExtensionsFixture.cs, tests/projects/SdkNet8Alias/Class1.cs, tests/projects/SdkNet8Alias/SdkNet8Alias.csproj, tests/projects/SdkNet8Alias/UnitTest1.cs, tests/projects/TestProjects.sln
This PR adds explicit support for [assembly aliases](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/inputs#references), that is the ability to add a prefix (_an alias_) to the namespace(s) of one or more assemblies in order to deal with name conflict.
This PR adds a `ReferenceAliases` property to `IAnalyzerResult` interface. This property exposes a dictionary providing the list of aliases for every aliased references. If a referenced assembly is not aliased, it will not be listed in this dictionary.
This property is also used for Roslyn Workspace building.
A dedicated test project (`SdkNet8Alias`) has been added and is used in integration tests and workspace tests.
=> Add explicit support for assembly aliases

Directory.Build.props, src/Buildalyzer.Workspaces/Buildalyzer.Workspaces.csproj, src/Buildalyzer/Buildalyzer.csproj, tests/Buildalyzer.Tests/Buildalyzer.Tests.csproj, tests/Buildalyzer.Workspaces.Tests/Buildalyzer.Workspaces.Tests.csproj
Applied suggestions of [.NET project file analyzers](https://dotnet-project-file-analyzers.github.io).
=> Minor improvements

.github/workflows/build.yml
The builds now fail stating that MacOS-12 has been deprecated.
=> Use MacOS-13

src/Buildalyzer.Logger/BuildalyzerLogger.cs, tests/Buildalyzer.Tests/Integration/Failing_builds.cs, tests/Buildalyzer.Workspaces.Tests/Failing_builds.cs, tests/projects/BuildWithError/BuildWithError.MultiTarget.csproj, tests/projects/BuildWithError/BuildWithError.csproj, tests/projects/BuildWithError/MissingSemiColon.cs, tests/projects/BuildWithError/UnclosedClass.cs
There is no test coverage - as far as I could find - that detects what happens when a build is failing. I'm not sure if I am doing something wrong, or that although there are compilation errors, the `BuildFinishedEventsArgs` and `TargetFinishedEventsArgs` communicate `Successful = true`.
=> Create tests that detect failing builds
